task: 'genebody'
subject: 'zhanghongwei'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'gb_zhanghongwei_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'gb_zhanghongwei_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'gb_zhanghongwei_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'gb_zhanghongwei_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'gb_zhanghongwei_test'

eval:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'gb_zhanghongwei_eval'

eval_pose:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'gb_zhanghongwei_eval_pose'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
