task: 'humman'
subject: 'p000452_a000208'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000452_a000208_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000452_a000208_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000452_a000208_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'hm_p000452_a000208_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'hm_p000452_a000208_test'

eval:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000452_a000208_eval'

eval_pose:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000452_a000208_eval_pose'
bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
