task: 'yt_videos'
subject: 'yt_test0'
experiment: 'debug'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ytv_yt_test0_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ytv_yt_test0_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ytv_yt_test0_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'ytv_yt_test0_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'ytv_yt_test0_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5


# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
