task: 'h36m'
subject: 'S1_Walking'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S1_Walking_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S1_Walking_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S1_Walking_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'h36m_S1_Walking_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'h36m_S1_Walking_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
