task: 'humman'
subject: 'p000475_a000063'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000475_a000063_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000475_a000063_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000475_a000063_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'hm_p000475_a000063_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'hm_p000475_a000063_test'

eval:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000475_a000063_eval'

eval_pose:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p000475_a000063_eval_pose'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
