task: 'humman'
subject: 'p100047_a001425'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p100047_a001425_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p100047_a001425_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p100047_a001425_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'hm_p100047_a001425_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'hm_p100047_a001425_test'

eval:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p100047_a001425_eval'

eval_pose:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p100047_a001425_eval_pose'

vis:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'hm_p100047_a001425_vis'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
