task: 'deform'
gpus: [0]

parent_cfg: 'configs/defaults.yaml'

test_dataset_module: 'lib.datasets.tpose_pdf_dataset_eval'
test_dataset_path: 'lib/datasets/tpose_pdf_dataset_eval.py'

train_dataset:
    data_root: 'data/humman123/sequences/p000542_a000048'
    human: 'CoreView_p000542_a000048'
    ann_file: 'data/humman123_eval/CoreView_p000542_a000048/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/humman123/sequences/p000542_a000048'
    human: 'CoreView_p000542_a000048'
    ann_file: 'data/humman123/CoreView_p000542_a000048/annots.npy'
    split: 'test'

test:
    frame_sampler_interval: 1

# data options
H: 1080 
W: 1920
ratio: 0.5
training_view: [0, 6, 12, 18]
init_aninerf: 'no_pretrain'
num_train_frame: 300
num_eval_frame: 400
begin_ith_frame: 0
frame_interval: 1
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
use_bigpose: True
big_box: True
box_padding: 0.05

bbox_offset: 0.3

### KK ###
progress_cfg:
    # train_dataset_module: 'lib.datasets.tpose_pdf_pose_sequence_dataset'
    # train_dataset_path: 'lib/datasets/tpose_pdf_pose_sequence_dataset.py'
    # test_dataset_module: 'lib.datasets.tpose_pdf_pose_sequence_dataset'
    # test_dataset_path: 'lib/datasets/tpose_pdf_pose_sequence_dataset.py'
    train_dataset_module: 'lib.datasets.movement_progress'
    train_dataset_path: 'lib/datasets/movement_progress.py'
    test_dataset_module: 'lib.datasets.movement_progress'
    test_dataset_path: 'lib/datasets/movement_progress.py'

    renderer_module: 'lib.networks.renderer.tpose_renderer_mmsk'
    renderer_path: 'lib/networks/renderer/tpose_renderer_mmsk.py'

    visualizer_module: 'lib.visualizers.if_nerf_progress'
    visualizer_path: 'lib/visualizers/if_nerf_progress.py'

    test_dataset:
        data_root: 'data/humman123_eval/p000542_a000048'
        human: 'CoreView_p000542_a000048'
        ann_file: 'data/humman123_eval/CoreView_p000542_a000048/annots.npy'
        split: 'test'

    test:
        sampler: ''

    training_view: [0]
    # num_train_frame: 10
    # frame_interval: 80
##########