task: 'humman'
subject: 'p000489_a000049'
experiment: 'single_gpu'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'humman_p000489_a000049_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'humman_p000489_a000049_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'humman_p000489_a000049_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'humman_p000489_a000049_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'humman_p000489_a000049_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5


# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
