task: 'people_snapshot'
subject: 'female-1-casual'
experiment: 'single_gpu'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ps_female-1-casual_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ps_female-1-casual_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ps_female-1-casual_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'ps_female-1-casual_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'ps_female-1-casual_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5


# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
