task: 'yt_videos'
subject: 'yt_test0'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ytv_yt_test0_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ytv_yt_test0_train_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'ytv_yt_test0_train_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'ytv_yt_test0_train_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'ytv_yt_test0_train_test'


bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
