task: 'zju_mocap'
subject: 'p313'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_313_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_313_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_313_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_313_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_313_test'

eval:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_313_eval'


bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
