task: 'deform'
gpus: [0]

parent_cfg: 'configs/defaults.yaml'

# train_dataset:
#     data_root: 'data/light_stage/CoreView_390'
#     human: 'CoreView_390'
#     ann_file: 'data/light_stage/CoreView_390/annots.npy'
#     split: 'train'

# test_dataset:
#     data_root: 'data/light_stage/CoreView_390'
#     human: 'CoreView_390'
#     ann_file: 'data/light_stage/CoreView_390/annots.npy'
#     split: 'test'

### KK ###
## 替换light_stage为zju-mocap
train_dataset:
    data_root: 'data/zju_mocap/390'
    human: 'CoreView_390'
    ann_file: 'data/zju_mocap/CoreView_390/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/390'
    human: 'CoreView_390'
    ann_file: 'data/zju_mocap/CoreView_390/annots.npy'
    split: 'test'

test:
    frame_sampler_interval: 30

# data options
# H: 1002
# W: 1000
ratio: 0.5
training_view: [0, 6, 12, 18]
init_aninerf: 'no_pretrain'
num_train_frame: 800
num_eval_frame: 1000
begin_ith_frame: 0
frame_interval: 1
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
use_bigpose: True
big_box: True
box_padding: 0.05

bbox_offset: 0.3

### KK ###
progress_cfg:
    # train_dataset_module: 'lib.datasets.tpose_pdf_pose_sequence_dataset'
    # train_dataset_path: 'lib/datasets/tpose_pdf_pose_sequence_dataset.py'
    # test_dataset_module: 'lib.datasets.tpose_pdf_pose_sequence_dataset'
    # test_dataset_path: 'lib/datasets/tpose_pdf_pose_sequence_dataset.py'
    train_dataset_module: 'lib.datasets.movement_progress'
    train_dataset_path: 'lib/datasets/movement_progress.py'
    test_dataset_module: 'lib.datasets.movement_progress'
    test_dataset_path: 'lib/datasets/movement_progress.py'

    renderer_module: 'lib.networks.renderer.tpose_renderer_mmsk'
    renderer_path: 'lib/networks/renderer/tpose_renderer_mmsk.py'

    visualizer_module: 'lib.visualizers.if_nerf_progress'
    visualizer_path: 'lib/visualizers/if_nerf_progress.py'

    test_dataset:
        data_root: 'data/zju_mocap/390'
        human: 'CoreView_390'
        ann_file: 'data/zju_mocap/CoreView_390/annots.npy'
        split: 'test'

    test:
        sampler: ''

    training_view: [0]
    # num_train_frame: 10
    # frame_interval: 80
##########